# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Lint and Test fred-py-api

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests coverage black==22.6.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      run: |
        # Run black on all Python files
        black --line-length 120 --check ./
    - name: Test with coverage
      run: |
        coverage run -m unittest discover -s tests
        coverage report -m
